import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("the root package entry loads without react installed", async () => {
  const module = await import("../dist/index.js");

  assert.equal(typeof module.enhanceTable, "function");
  assert.equal(typeof module.copySelectionToText, "function");
});

test("the browser assets are generated during build", async () => {
  const packageJson = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8")) as {
    version: string;
  };
  const browserBundle = await readFile(new URL("../dist/browser.js", import.meta.url), "utf8");
  const bookmarklet = await readFile(new URL("../dist/bookmarklet.txt", import.meta.url), "utf8");
  const inlineBookmarklet = await readFile(new URL("../dist/bookmarklet.inline.txt", import.meta.url), "utf8");
  const bookmarkletLoader = await readFile(new URL("../dist/bookmarklet-loader.js", import.meta.url), "utf8");
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");

  assert.match(browserBundle, /TableSteroids/);
  assert.match(bookmarklet, /^javascript:/);
  assert.match(bookmarklet, /Enabling table steroids/);
  assert.match(bookmarklet, /Script not allowed\./);
  assert.match(bookmarklet, /table-steroids-bookmarklet-toast/);
  assert.match(bookmarklet, /runFallback/);
  assert.match(bookmarklet, /Trying latest published build/);
  assert.match(bookmarklet, /Script not allowed, using offline version\./);
  assert.match(bookmarklet, /Using online latest version\./);
  assert.match(bookmarklet, /trustedTypes/);
  assert.match(bookmarklet, /createScriptURL/);
  assert.match(bookmarklet, /cdn\.jsdelivr\.net\/npm\/table-steroids\/dist\/bookmarklet-loader\.js/);
  assert.match(bookmarklet, /Table steroids enabled/);
  assert.match(inlineBookmarklet, /^javascript:/);
  assert.match(inlineBookmarklet, /__tableSteroidsBookmarkletSource__="inline"/);
  assert.match(inlineBookmarklet, /TableSteroids/);
  assert.match(inlineBookmarklet, /Table steroids enabled/);
  assert.match(inlineBookmarklet, /inline bundled version/);
  assert.match(inlineBookmarklet, new RegExp(`v${packageJson.version}`));
  assert.doesNotMatch(inlineBookmarklet.trim(), /[\r\n]/);
  assert.doesNotMatch(inlineBookmarklet, / {2,}/);
  await assert.rejects(readFile(new URL("../dist/bookmarklet.github.txt", import.meta.url), "utf8"), { code: "ENOENT" });
  assert.match(readme, /For app developers/);
  assert.match(readme, /For non-developers/);
  assert.match(readme, /Enhance any table across the web without installing anything by using a bookmarklet/);
  assert.match(readme, /Paste this into the bookmark URL or location field/);
  assert.match(readme, /dist\/bookmarklet\.inline\.txt/);
  assert.match(readme, /tries the latest published build first, then falls back to the embedded build/);
  assert.match(readme, /latest version/);
  assert.match(readme, /offline version/);
  assert.match(readme, /do not want script injection at all/);
  assert.match(readme, /inline bundled version/);
  assert.match(readme, /Script not allowed\./);
  assert.match(bookmarkletLoader, /Table steroids enabled/);
  assert.match(bookmarkletLoader, /Table steroids disabled/);
  assert.match(bookmarkletLoader, new RegExp(`v${packageJson.version}`));
  assert.match(bookmarkletLoader, /latest version/);
  assert.match(bookmarkletLoader, /offline version/);
  assert.match(bookmarkletLoader, /inline bundled version/);
  assert.match(bookmarkletLoader, /https:\/\/github\.com\/sajadmh\/table-steroids/);
  assert.match(bookmarkletLoader, /offlineLink\.href=repoUrl/);
  assert.match(bookmarkletLoader, /const subtitleColor="rgba\(255,255,255,0\.65\)"/);
  assert.match(bookmarkletLoader, /const subtitleFont="500 11px\/1\.2 system-ui,sans-serif"/);
  assert.match(bookmarkletLoader, /offlineLink\.style\.color=subtitleColor/);
  assert.match(bookmarkletLoader, /offlineLink\.style\.font=subtitleFont/);
  assert.match(bookmarkletLoader, /offlineLink\.style\.textDecorationColor=subtitleColor/);
  assert.match(bookmarkletLoader, /toast\.style\.pointerEvents=sourceType==="fallback"\?"auto":"none"/);
  assert.match(bookmarkletLoader, /statusDot\.style\.backgroundColor=statusColor/);
  assert.match(bookmarkletLoader, /Activated/);
  assert.match(bookmarkletLoader, /source: sourceValue/);
  assert.match(browserBundle, /clipboardCell\.append\(\.\.\.Array\.from\(sourceCell\.element\.childNodes, \(node\) => node\.cloneNode\(true\)\)\)/);
  assert.doesNotMatch(browserBundle, /clipboardCell\.innerHTML = sourceCell\.element\.innerHTML/);
  assert.match(bookmarkletLoader, /versionText\.textContent/);
  assert.match(bookmarkletLoader, /version\.style\.color=subtitleColor/);
  assert.match(bookmarkletLoader, /version\.style\.font=subtitleFont/);
  assert.match(bookmarkletLoader, /toast\.append\(label,version\)/);
  assert.match(bookmarkletLoader, /table-steroids-bookmarklet-toast/);
  assert.match(bookmarkletLoader, /5000/);
});
